# Generated by Django 2.0.2 on 2019-10-19 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0002_auto_20191019_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetutorial',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 17, 3, 5, 474303)),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 17, 3, 5, 478291)),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 17, 3, 5, 468318)),
        ),
    ]
