# Generated by Django 2.0.2 on 2019-10-19 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0005_auto_20191019_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_materials', to='eLearning.CourseTutorial'),
        ),
        migrations.AlterField(
            model_name='coursetutorial',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 14, 49, 167057)),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 14, 49, 175118)),
        ),
        migrations.AlterField(
            model_name='material',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 14, 49, 161488)),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_videos', to='eLearning.CourseTutorial'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 14, 49, 149395)),
        ),
    ]
