# Generated by Django 2.0.2 on 2019-10-20 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0006_auto_20191019_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='coursetutorial',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursetutorial',
            name='tot_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coursetutorial',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 16, 21, 2, 424726)),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 16, 21, 2, 433832)),
        ),
        migrations.AlterField(
            model_name='material',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 16, 21, 2, 420665)),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 16, 21, 2, 407947)),
        ),
        migrations.AddField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ratings', to='eLearning.CourseTutorial'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ratings', to='eLearning.Student'),
        ),
    ]
