# Generated by Django 2.0.2 on 2019-10-20 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning', '0007_auto_20191020_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='coursetutorial',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 17, 47, 27, 596611)),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 17, 47, 27, 602750)),
        ),
        migrations.AlterField(
            model_name='material',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 17, 47, 27, 595584)),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 17, 47, 27, 581984)),
        ),
    ]
